CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY, username VARCHAR(255) NOT NULL, email VARCHAR(255) NULL, "type" VARCHAR(255) NOT NULL, slackId VARCHAR(20) NULL, "delete" BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE IF NOT EXISTS forks (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL, last_updated_at TIMESTAMP NOT NULL, pushed_at TIMESTAMP NOT NULL, "delete" BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT fk_forks_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS commits ("commit" CHAR(40) PRIMARY KEY, message TEXT NOT NULL, author BIGINT NULL, commiter BIGINT NULL, parents_count INT NOT NULL, created_at BIGINT NOT NULL, commited_at BIGINT NOT NULL, CONSTRAINT fk_commits_author__id FOREIGN KEY (author) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_commits_commiter__id FOREIGN KEY (commiter) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS commit_parents ("commit" CHAR(40), parent CHAR(40), CONSTRAINT pk_commit_parents PRIMARY KEY ("commit", parent), CONSTRAINT fk_commit_parents_commit__commit FOREIGN KEY ("commit") REFERENCES commits("commit") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_commit_parents_parent__commit FOREIGN KEY (parent) REFERENCES commits("commit") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS heads (repo_id BIGINT, branch VARCHAR(255), "commit" CHAR(40) NOT NULL, CONSTRAINT pk_heads PRIMARY KEY (repo_id, branch), CONSTRAINT fk_heads_commit__commit FOREIGN KEY ("commit") REFERENCES commits("commit") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS records (host VARCHAR(24), "name" VARCHAR(255), "type" VARCHAR(10), "state" VARCHAR(10) NOT NULL, current_value JSON NULL, CONSTRAINT pk_records PRIMARY KEY (host, "name", "type"));
CREATE TABLE IF NOT EXISTS record_timelines (host VARCHAR(24), "name" VARCHAR(255), "type" VARCHAR(10), timeline_type VARCHAR(10) NOT NULL, old_value JSON NULL, current_value JSON NULL, "commit" CHAR(40), "timestamp" TIMESTAMP NOT NULL, CONSTRAINT pk_record_timelines PRIMARY KEY (host, "name", "type", "commit"), CONSTRAINT fk_record_timelines_commit__commit FOREIGN KEY ("commit") REFERENCES commits("commit") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS fork_proposals (host VARCHAR(24), "name" VARCHAR(255), "type" VARCHAR(10), repository VARCHAR(255), branch VARCHAR(255), merge_base VARCHAR(64) NOT NULL, "state" VARCHAR(20) NOT NULL, current_value JSON NULL, base_value JSON NULL, CONSTRAINT pk_fork_proposals PRIMARY KEY (host, "name", "type", repository, branch));
CREATE TABLE IF NOT EXISTS fork_proposal_timelines (host VARCHAR(24), "name" VARCHAR(255), "type" VARCHAR(10), repository VARCHAR(255), branch VARCHAR(255), event_type VARCHAR(10) NOT NULL, old_value JSON NULL, new_value JSON NULL, "commit" CHAR(40), "timestamp" TIMESTAMP NOT NULL, CONSTRAINT pk_fork_proposal_timelines PRIMARY KEY (host, "name", "type", repository, branch, "commit"), CONSTRAINT fk_fork_proposal_timelines_commit__commit FOREIGN KEY ("commit") REFERENCES commits("commit") ON DELETE RESTRICT ON UPDATE RESTRICT);
